WomenAccessoriesShop/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WomenAccessoriesShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WomenAccessoriesShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WomenAccessoriesShop.Models;
using WomenAccessoriesShop.ViewModels;

namespace WomenAccessoriesShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IAccessoryRepository _accessoryRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IAccessoryRepository accessoryRepository, ShoppingCart shoppingCart)
        {
            _accessoryRepository = accessoryRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartVM
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int accessoryId)
        {
            var selectedAccessory = _accessoryRepository.GetAccessories().FirstOrDefault(p => p.AccessoryId == accessoryId);

            if (selectedAccessory != null)
            {
                _shoppingCart.AddToCart(selectedAccessory, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int accessoryId)
        {
            var selectedPie = _accessoryRepository.GetAccessories().FirstOrDefault(p => p.AccessoryId == accessoryId);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
    }
}

WomenAccessoriesShop/Views/Shared/AccessoryItem.cshtml
@model Accessory

<div class="col-sm-3 col-lg-3 col-md-3">
    <div class="thumbnail">
        <img src="@Model.ImageUrl" alt="" style="width:200px; height:250px;">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Home" asp-action="Details" asp-route-id="@Model.AccessoryId">@Model.Name</a>
            </h3>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-accessoryId="@Model.AccessoryId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

WomenAccessoriesShop/Views/Shared/Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/Glasses_1.jpg" alt="" style="height:50px;">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/LongGLoves_2.jpg" alt="" style="height:50px;">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/Ring_3.jpg" alt="" style="height:50px;">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

WomenAccessoriesShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Women Accessories Shop</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="index"></a></li>
                    @await Component.InvokeAsync("ShoppingCartSummery")
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    @RenderSection("scripts",false)
</body>
</html>